---
title: आरजीबी रंग
hero_image: इमेजेस/बॅनर.पीएनजी
description: आरजीबी रंगांचे एक साधे स्पष्टीकरण
theme: लाल #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: क्रिएटर, डिझाईन -०, प्रोग्रामिंग -०, फिजिकल कम्प्युटिंग -०, मनुफॅक्चर -०, कम्युनिटी -०
interests: "प्राणी, विनोद / खोड्या, जागा, छायाचित्रण, निसर्ग / बाहेरील / हवामान, संगीत / आवाज, भौतिक संगणन, खेळ, रोबोट्स, भूगोल"
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - 
    title: Introduction
