---
title: RGB रंग
hero_image: images/banner.png
description: RGB रंगों की एक सरल व्याख्या
theme: red
duration: 0
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: animals, jokes/pranks, space, photography, nature/outside/weather, music/sound, physical computing, games, robots, geography
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - 
    title: परिचय
