---
title: RGB रंग
hero_image: images/banner.png
description: RGB रंगों की एक सरल व्याख्या
theme: लाल
duration: 0
listed: false
ingredient: true
copyedit: true
curriculum: निर्माता, डिज़ाइन-०, प्रोग्रामिंग-०, भौतिक-Comp-०, निर्माण-०, समुदाय-०
interests: "जानवरों, चुटकुले/मज़ाक, अंतरिक्ष, फोटोग्राफी, प्रकृति/बाहर/मौसम, संगीत/ध्वनि, शारीरिक कंप्यूटिंग, खेल, रोबोट, भूगोल"
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - 
    title: परिचय
