---
title: RGB-farger
hero_image: images/banner.png
description: En enkel forklaring av RGB-farger
theme: rød #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "dyr, vitser/spøker, romfart, fotografi, natur/utendørs/vær, musikk/lyd, fysisk databehandling, spill, roboter, geografi"
technologies: "elektronikk, sense-hat, fysiskfysisk databehandling, html, scratch, python"
site_areas:
steps:
  - 
    title: Introduksjon
