---
title: RGB colours
hero_image: images/banner.png
description: A simple explanation of RGB colours
theme: đỏ #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: tác giả, thiết kế-0, lập trình-0, phys-comp-0, sản xuất-0, cộng đồng-0
interests: "animals, jokes/pranks, space, photography, nature/outside/weather, music/sound, physical computing, games, robots, geography"
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - 
    title: Giới thiệu
