---
title: Modelul de culoare RGB (rosu-verde-albastru)
hero_image: images/banner.png
description: O explicație simplă a culorilor RGB
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programare-0, fiz-comp-0, fabricare-0, comunitate-0
interests: "animale, glume/farse, spațiu, fotografie, natură/exterio /vreme, muzică/sunet, calcul fizic, jocuri, roboți, geografie"
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - 
    title: Introducere
