---
title: ಆರ್ ಜಿ ಬಿ (RGB) ಬಣ್ಣಗಳು
hero_image: images/banner.png
description: ಆರ್ಜಿಬಿ ಬಣ್ಣಗಳ ಸರಳ ವಿವರಣೆ
theme: ಕೆಂಪು #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: ಸೃಷ್ಟಿಕರ್ತ, ವಿನ್ಯಾಸ -0, ಪ್ರೋಗ್ರಾಮಿಂಗ್ -0, ಭೌತಿಕ-ಕಂಪ್ -0, ಉತ್ಪಾದನೆ -0, ಸಮುದಾಯ -0
interests: "animals, jokes/pranks, space, photography, nature/outside/weather, music/sound, physical computing, games, robots, geography"
technologies: "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್, ಸೆನ್ಸ್-ಹ್ಯಾಟ್, ಫಿಸಿಕಲ್ ಕಂಪ್ಯೂಟಿಂಗ್, HTML / CSS, ಸ್ಕ್ರ್ಯಾಚ್, ಪೈಥಾನ್"
site_areas:
steps:
  - 
    title: ಪರಿಚಯ
