---
title: RGB colours
hero_image: صور/ شعار
description: شرح بسيط لألوان RGB.
theme: أحمر #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: المبتكر، التصميم-0، البرمجة 0، الفيزياء-كوم-0، التصنيع 0، المجتمع 0
interests: "الحيوانات ، النكات / المقالب ، الفضاء ، التصوير الفوتوغرافي ، الطبيعة / الخارج / الطقس ، الموسيقى / الصوت ، الحوسبة الفيزيائية ، الألعاب ، الروبوتات ، الجغرافيا"
technologies: "الإلكترونيات ، قبعة الإحساس ، الحوسبة الفيزيائية ، html / css ، scratch ، python"
site_areas:
steps:
  - 
    title: المقدمة
