---
title: RGB colours
hero_image: images / banner.png
description: A simple explanation of RGB colours
theme: 빨간
duration: 2
listed: false
ingredient: true
copyedit: true
curriculum: 작성자, 디자인 -0, 프로그래밍 -0, phys-comp-0, 제조 -0, 커뮤니티 -0
interests: "animals, jokes/pranks, space, photography, nature/outside/weather, music/sound, physical computing, games, robots, geography"
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - 
    title: 소개
