---
title: RGB farby
hero_image: images/banner.png
description: Jednoduché vysvetlenie RGB farieb
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "zvieratá, vtipy/žarty, vesmír, fotografia, príroda/vonku/počasie, hudba/zvuk, počítače prepojené s fyzickým svetom, hry, roboty, geografia"
technologies: "elektronika, senzorová karta, počítač prepojený s fyzickým svetom, html/css, scratch, python"
site_areas:
steps:
  - 
    title: Úvod
