---
title: RGB වර්ණ
hero_image: images / banner.png
description: RGB වර්ණ පිළිබඳ සරල පැහැදිලි කිරීමක්
theme: රතු #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: නිර්මාණකරු, සැලසුම්-0, කේතන වැඩසටහන්-0, භෞතික-පරිගනක-0, නිෂ්පාදනය-0, ප්‍රජා-0
interests: "සතුන්, විහිළු / රැවටීම් , අවකාශය, ඡායාරූපකරණය, සොබාදහම / අවට / කාලගුණය, සංගීතය / ශබ්ද, භෞතික පරිගණකකරණය, ක්‍රීඩා, රොබෝවරු, භූගෝලය"
technologies: "ඉලෙක්ට්‍රොනික්, sense-hat, භෞතික පරිගණක කරණය, html / css, scratch, python"
site_areas:
steps:
  - 
    title: හැදින්වීම
