---
title: RGB renkler
hero_image: images/banner.png
description: RGB renklerinin basit bir açıklaması
theme: kırmızı #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "hayvanlar, şakalar, uzay, fotoğrafçılık, doğa/dış mekan/hava, müzik/ses, fiziksel bilgi işlem, oyunlar, robotlar, coğrafya"
technologies: "elektronik, sense-hat, fiziksel bilgi işlem, html/css, scratch, python"
site_areas:
steps:
  - 
    title: Giriş
